### ISSUE TITLE
Add playlist support

### ISSUE THREAD

**Issue by kelsos** [kelsos/mbrc#11]
Add support for playlist view, edit, manage, play functionality.

**Comment by tom-sherman** [comment]
Has any work been done on this?

**Comment by kelsos** [comment]
Only on the development branch, however the development has been a complete rewrite and requires a lot of work on the client

**Comment by kelsos** [comment]
v1.0.0 has a pretty basic playlist support. You can browse and press to play playlists.
This will be enhanced with extra management functionality on v2.0.0
