### ISSUE TITLE
Library browsing functionality

### ISSUE THREAD

**Issue by kelsos** [kelsos/mbrc#19]
Implement the ability to browse the tracks in the library

**Comment by mollierobbert** [comment]
How far did you get with this? There doesn't seem to be a library overview on the Google Play version.

**Comment by kelsos** [comment]
There are currently two versions, the one requires effort (development branch) to be in a release state (it is a complete rewrite of the whole application and plugin and uses web techonologies, HTTP and websockets for communication).

The other is on the legacy-improvements branch that uses the existing mechanism and it should be in a beta state soon enough.

**Comment by mollierobbert** [comment]
Cool. Anything I can do to help on the legacy branch?

**Comment by kelsos** [comment]
I am closing the issue since there nothing extra that needs to be done on this at the moment
