### ISSUE TITLE
Add headset button controls

### ISSUE THREAD

**Issue by lylebrown** [kelsos/mbrc#36]
Allow use of headset button to control tracks (Pause/play on single click, next track on double click). Should be a standard library for Android - I'll investigate a bit and report back with any leads.

This is useful when Musicbee Remote is used in combination with WiFi Audio or a similar application.

**Comment by kelsos** [comment]
Single click for play pause works in cea4284df489e9141fcfd47b714e187746b4d810 I am not sure about the double click I have to check it before closing the issue

**Comment by kelsos** [comment]
This feature has been released with version 0.10.
