### ISSUE TITLE
Search / Play Now bug

### ISSUE THREAD

**Issue by neilhump** [kelsos/mbrc#40]
To recreate:

Have a collection of music with albums of the same name. In my case I have several with the name of "Very Best Of" (no other text in the album title).

Search for Artist "XYZ"

Returns 1 result of XYZ.

Click the dots and Get albums for XYZ

Returns among others, "Very Best Of" XYZ 

Click either Get Tracks or Play Now on the "Very Best Of" album for artist XYZ causes all tracks to be returned that have an album title of "Very Best Of", regardless of artist, when it should presumably return just the tracks on XYZ's "Very Best Of" album.

Edit: Please delete if this is the incorrect place to report this. Thanks.

**Comment by kelsos** [comment]
This should be fixed in the upcoming v1.0.0 since the mechanism for queing tracks has been updated.
