### ISSUE TITLE
Could not find com.android.support:support-v13:22.1.1  Error while checkout [Question]

### ISSUE THREAD

**Issue by LOG-TAG** [kelsos/mbrc#58]
Can anybody help me to solve this error 

![selection_141](https://cloud.githubusercontent.com/assets/1190344/8081964/1ee49ca0-0f97-11e5-8beb-719e8a972790.png)

**Comment by kelsos** [comment]
Do you have the google support repository synchronized, I suppose this is part of the development branch. Keep in mind that this differs greatly from the master, v0.11 branch and requires the development version of the plugin.

**Comment by LOG-TAG** [comment]
Issue solved ! Thanks for your time.

Details:
I'm using Ubuntu Linux  !! 

Thanks for pointing out "sync the sdk repository folder to your local maven repository"  

May be this the possible bug https://code.google.com/p/android/issues/detail?id=69270, 
solved the issue by: http://stackoverflow.com/questions/30287022/cant-iterate-over-compile-dependecies-due-to-support-library

New issue with compile 'com.mobeta.android.dslv:drag-sort-listview:0.6.1 since it's no longer supported !!  I have to import it as local lib !!

Note: I'm trying to learn the GreanDAO+ Content provider generator (by inspired with your blog !) :)

**Comment by kelsos** [comment]
For dslv I have an artifact uploaded on bintray
provided by the following dependency in the build script

```
maven { url 'http://dl.bintray.com/kelsos/maven' }
```
