### ISSUE TITLE
Porting from Roboguice to Dagger 2 to increase performance [enhancement]

### ISSUE THREAD

**Issue by LOG-TAG** [kelsos/mbrc#63]
Roboguice to Dagger 2 will be a good move! it's a challenging part though (learning curve for Dagger 2) , also we need to change the code generator code !!!

**Comment by kelsos** [comment]
I will consider it for the future though I tried dagger a little bit and I have to admit that I prefer Roboguice. At the moment other work has to be done and my available time is minimal due to work.

**Comment by kelsos** [comment]
The legacy branch now uses https://github.com/stephanenicolas/toothpick.
The plan is to also migrate the development branch to toothpick after v1.0.0 is released probably
