### ISSUE TITLE
Add server auto-reconnect 

### ISSUE THREAD

**Issue by r0x0r** [kelsos/mbrc#64]
It would be nice if the application would periodically check for connection to the server and automatically re-connect if the connection is dropped.

**Comment by r0x0r** [comment]
Upgraded to Marshmellow and now Musicbee Remote loses connection every time I lock the phone.

**Comment by kelsos** [comment]
OK I will check it as soon as possible

**Comment by kelsos** [comment]
In v1.0.0 there is a ping mechanism in place that will restart the connection if the reply is not received in time.
Also while connected the service/notification runs on foreground. 
The latest versions of Android will kill and not restart a background service if it is not foreground. So with this change the service should be more resilient while connected.
